### PR TITLE
Fallback to ratpack execution to get current spans

### PR DESCRIPTION
**Pull request by edwardsoo-ss**
this will allow propagating current spans to execution of ratpack's parallel batch

usage:

```java
List<Promise> promises = ...;
Span maybeLocalSpan = ...;
ServerSpan maybeServerSpan = ...;
return ParallelBatch.of(promises)
	.execInit(e -> {
		if (maybeLocalSpan != null) {
			e.add(new RatpackServerClientLocalSpanState.CurrentLocalSpanValue(maybeLocalSpan));
		}
		if (maybeServerSpan != null) {
			e.add(new RatpackServerClientLocalSpanState.CurrentServerSpanValue(maybeServerSpan));
		}
	})
	.yield();
```

@hyleung @llinder @Bijnagte @jeff-blaisdell take a look please

### CODE REVIEW

**Comment by hyleung** [comment]
@edwardsoo-ss I'm not at all familiar with the `ParallelBatch` stuff, so could you elaborate on how this fallback logic works in that context? Does `Execution.current()` return something different when running in a `ParallelBatch`?

Also, I'm going to start looking at upgrading to Brave 4.x (see #22) - at the moment I don't know how that will look or whether it will change how this stuff will work.

**Comment by edwardsoo-ss** [comment]
hello @hyleung, quoting https://ratpack.io/manual/current/api/ratpack/exec/util/ParallelBatch.html, a `ParallelBatch` is:
> A batch of promises to be processed, in parallel.
> 
> Parallel batches can be created via `of(Iterable)`.
> 
> Each promise will be executed in a forked execution. The `execInit(Action)` method allows each forked execution to be customised before executing the work.

The problem is that the forked executions do not get the same `ratpack.registry.Registry` as the execution context that started them, so we need another way to pass the trace context.

I have also tried invoking `ratpack.zipkin.internal.RatpackServerClientLocalSpanState#setCurrentServerSpan` and `ratpack.zipkin.internal.RatpackServerClientLocalSpanState#setCurrentLocalSpan` inside `ratpack.exec.util.ParallelBatch#execInit` after getting references to the server and local span at the point of the parallel batch creation, but the block supplied to `execInit` is not executed on a Ratpack-managed thread and the span setters will throw `ratpack.exec.UnmanagedThreadException` (at `ratpack.exec.internal.DefaultExecution#require`)

Another workaround is to get references to current spans and pass them to the promises to be executed in parallel using closure, but that requires the promises code to be aware of the tracing that is going on.

I don't think upgrading to brave 4.x will change this problem, since this is related to implementation of `ParallelBatch`. I can re-submit this suggestion/change until after the API upgrade if you prefer.

**Comment by hyleung** [comment]
@edwardsoo-ss ah got it. So each `Promise` gets its own `Execution` via `fork`. And in the example you provided, you're passing the parent span into the closure?

**Comment by edwardsoo-ss** [comment]
@hyleung yes, in the example I pass the spans to the `execInit` closure.
Currently in our projects I pass the spans to the promise using closures which is a bit different:
```java
Span maybeLocalSpan = ...;
ServerSpan maybeServerSpan = ...;
HttpClient httpClient = ...;

List<Promise> promises = Collections.singletonList(httpClient.post(uri, request -> {
    if (maybeLocalSpan != null) {
        localTracer.currentSpan().setCurrentSpan(maybeLocalSpan);
    }
    if (maybeServerSpan != null) {
        serverTracer.currentSpan().setCurrentSpan(maybeServerSpan);
    }
    ...
}));

return ParallelBatch.of(promises)
	.yield();
```

I also see that @llinder has done the same work for the 4.1 upgrade https://github.com/hyleung/ratpack-zipkin/pull/24 so I will just close this for now. thanks!

**Pull request closed without merging**
