### PR TITLE
Updates to latest brave, supporting route-based span names

### PR DESCRIPTION
**Pull request by codefromthecrypt**
this tests the api design here https://github.com/openzipkin/brave/pull/602

### CODE REVIEW

**Comment by hyleung** [comment]
I guess once this stuff is moved into the adapter, we can deprecate or remove kludgy stuff from `SpanNameProvider` 😁

https://github.com/hyleung/ratpack-zipkin/blob/master/src/main/java/ratpack/zipkin/SpanNameProvider.java#L11-L25

**Comment by codefromthecrypt** [comment]
ok did the minimum here. We can decide whether or not to remove the span namer independently

**Comment by codefromthecrypt** [comment]
going to bump for a patch release in a bit

**Comment by codefromthecrypt** [comment]
ok ready to go. tested with the example app

screen shot 2018-02-23 at 10 25 36 pm

**Review by hyleung — APPROVED** [review]
Thanks!

**Pull request merged**
